package:
  name: pyxona
  version: {{ environ.get("GIT_DESCRIBE", "unknown_version")|replace("v", "")|replace("-", "_") }}
  
source:
  path: .
 
build:
  script: python setup.py install

requirements:
  build:
    - python
    - setuptools
    - pip
    - numpy
    - quantities

  run:
    - python
    - setuptools
    - pip
    - numpy
    - scipy
    - quantities

test:
  imports:
    - pyxona

about:
  home: https://github.com/CINPLA/pyxona/
  license: GPL
  license_file: LICENSE
