package:
    name: pyxona
    version: {{ environ.get("GIT_TAG", "0.0.0_custom")|replace("v", "")|replace("-", "_") }}
source:
    git_url: ..
build:
    #noarch: python
    script: python setup.py install
requirements:
    build:
        - python
        - setuptools
        - pip
        - numpy
        - scipy
        - quantities
    run:
        - python
        - setuptools
        - pip
        - numpy
        - scipy
        - quantities
test:
  imports:
      - pyxona
about:
    description: 'IO for expipe and neuroscience data'
    dev_url: https://github.com/CINPLA/pyxona
    license: GNU GPLv3
    license_family: GPL
    license_file: LICENSE
extra:
    recipe-maintainers:
        - dragly
