package:
  name: pyxona
  version: {{ environ.get("GIT_STRING", "0.0.0_custom")|replace("v", "")|replace("-", "_") }}

source:
  git_url: ..

build:
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python
    - setuptools
    - pip

  run:
    - python
    - setuptools
    - numpy
    - scipy
    - quantities

test:
  requires:
    - pytest
    - coverage
    - codecov
    - sphinx
    - quantities

  source_files:
    - tests
    - docs
  imports:
    - pyxona
  commands:
    - python -c "import exdir; print(exdir.__version__)"
    - coverage run --source tests -m py.test -s
    - coverage report # [py3k]
    - codecov # [py3k]
    - cd docs ; make doctest # [py3k]

about:
  home: https://github.com/CINPLA/pyxona/
  license: MIT
  license_file: LICENSE
